[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  # bu asagidaki adres backend her calistiginda resetleniyor, dikkat etmek lazim
  to = "https://11a3-85-96-3-80.ngrok-free.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login.html"
  to = "/dashboard/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard/dashboard.html"
  status = 200
  force = true
