[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://154.53.180.35/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login.html"
  to = "/dashboard/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to   = "ws://154.53.180.35/ws"
  status = 200
  force  = true
